### ISSUE TITLE
DateTimeSpinner value property

### ISSUE THREAD

**Issue by harry248** [BowlerHatLLC/feathers#1207]
The DateTimeSpinner keeps a reference to the Date object set through the value property and updates that objects properties while changing the date. To avoid consufion I think it should use a clone of the Date object instead.

**Comment by joshtynjala** [comment]
I disagree, but only in the general case. It should be expected that an object may be modified by a component. However, since Date doesn't dispatch any events when modified, it's not possible to keep other components in sync. I see that Flex creates a copy in its date components, and I suspect that this is the reason why. I'll make this change.
