### ISSUE TITLE
VideoPlayer plays only sound after end is being reached on iOS.

### ISSUE THREAD

**Issue by harry248** [BowlerHatLLC/feathers#1236]
On iOS, when a (local) video file has reached the end of playback, a following call to play() does only play sound but the video stays black. I have to call videoTexture_onRestore() manually.

**Comment by joshtynjala** [comment]
I can reproduce this issue.  The changes that I pushed to fix #1234 made it so that this issue happens on all platforms now (not just iOS). I suspect that if the event/callback for NetStream.Play.Complete doesn't happen, AIR has trouble restarting the video. However, I suspect that I can find a workaround, such as manually restoring the texture like you did.

**Comment by harry248** [comment]
:+1:

**Comment by harry248** [comment]
That fixed the problem but now under iOS the app crashes or freezes silently after VideoPlayer.dispose() is  being called (more exactly in line 833 where you call this._texture.dipose();).

**Comment by joshtynjala** [comment]
I'm not able to reproduce that issue, but I'll switch them.
