### ISSUE TITLE
Simpler, more elegant way for dispose list's data provider.

### ISSUE THREAD

**Issue by khoamoc** [BowlerHatLLC/feathers#1238]
Hi, I found the dispose method of ListCollection cubersome, because you have to manually list all the "fields" of accessory for it to work.

------------

Your approach:

    this._list.dataProvider.dispose(   function (item:Object):void{
        DisplayObject(item.accessoryField1).dispose();
        DisplayObject(item.accessoryField2).dispose();
        ... ( we have to manually list all item's accessory fields here)
        DisplayObject(item.accessoryFieldn).dispose();
    });

------------

My approach ( simpler and more error prone, will automatically dispose ALL display objects and texture,  no need to list all the fields , I hope after enhancement, we only have to write :    this._list.dataProvider.dispose();

    this._list.dataProvider.dispose(   function (item:Object):void   {
        for (var i:* in item){

            if(item[i] is DisplayObject){
                item[i].dispose();
            }	

            if(item[i] is Texture){
                item[i].dispose();
            }
		
        }	
     });

OR simpler version:

    this._list.dataProvider.dispose( function (item:Object):void{
    
        for (var i:* in item){

            if( item[i] is DisplayObject || item[i] is Texture ){
                item[i].dispose();
            }

        }	
    });

**Comment by joshtynjala** [comment]
Thanks for the suggestion! However, as you correctly identified, your proposed approach is more error prone. It may not identify all objects in an item that may need to be disposed. That is why I required a function to be passed in to dispose(). If you are certain that you will always structure your data provider in a way that your function will never fail, then you can easily create a static utility function to pass to dispose() so that you don't need to rewrite it every time.
