### ISSUE TITLE
TokenList: avoid alloc on repeated call to "value"

### ISSUE THREAD

**Issue by Klug76** [BowlerHatLLC/feathers#1241]
The current version of the TokenList makes a memory alloc on every "get value" call:
```
		public function get value():String
		{
			return names.join(" ");
		}
```
```
			var t: TokenList = new TokenList();
			t.add("foo");
			t.add("bar");
			trace(System.totalMemory);
			for (var i: int = 0; i < 10000; ++i)
				t.value;
			trace(System.totalMemory);
```
Sample output:
```
12918784
12992512
```
It would be better to cache result.

**Comment by joshtynjala** [comment]
How often are you getting the TokenList's value? Could you call contains() instead?

This certainly could be optimized, but it will require some mildly tricky string manipulation in other functions like remove() and toggle(). I felt it was more important to focus on simplicity in these other functions because they are intended to be used more often, while getting or setting the full concatenated value should be a pretty uncommon situation.

**Comment by joshtynjala** [comment]
Actually, I could add a flag to determine if something has changed, and then only call join() if the flag is set. That's simpler, and I think that's what you were suggesting.

**Comment by Klug76** [comment]
You are right - this property is rarely used and is easily replaced by another (without allocation) (which I did in my game editor). Sorry for bothering you.
