### ISSUE TITLE
ScreenDensityScaleFactorManager for same physical size across devices?

### ISSUE THREAD

**Issue by chichilatte** [BowlerHatLLC/feathers#1244]
Just getting my head around `feathers.utils.ScreenDensityScaleFactorManager` – would it be right to say it tries to provide a starling stage whose display-objects are about the same physical size on any device? Similar to Android's "dp" density-independent pixels (where a fingertip is about 50dp)?

__Note:__
I've tested on a couple of phones and this doesn't quite seem to be the case. On the phone with the smaller screen my buttons are significantly smaller. Possibly to do with the reported `DeviceCapabilities.dpi`? For my test phones...

Phone | Reported DPI | Actual DPI
----------- | ----------- | -----------
Sony Xperia U (the smaller screen) | 240 | 280
Moto G 3rd gen | 320 | 294

I've also tried `Capabilities.screenDPI` and `Capabilities.serverString`'s `DP` variable – same reported DPI.

__Extra note:__ 
After more research I've found that screen densities on Android fall into [buckets] (http://forum.starling-framework.org/topic/capabilitiesscreendpi-giving-wrong-values), so reported DPI is often a bit off. Would still love an answer to my main question though.

**Comment by joshtynjala** [comment]
Yes, ScreenDensityScaleFactorManager is based on Android's density-independent pixels. It takes the value of Capabilities.screenDPI and chooses the nearest "density bucket". The physical sizes of buttons and things should be somewhat similar across different DPIs. However, the buckets are large enough that you may be able to notice some variation.

It's also worth nothing that Capabilities.screenDPI returns a DPI value chosen by the device manufacturer. Sometimes, the manufacturer chooses a DPI that doesn't actually match the real DPI of the screen. For instance, the original Samsung Galaxy Tab was an Android 2.x tablet, but Android hadn't yet been optimized for tablets. Samsung had these devices report a DPI that made the assets appear significantly larger, which allowed apps to continue using the phone layouts that they were optimized for. People used to think that AIR's Capabilities.screenDPI was reporting an incorrect value because it seemed wrong for a tablet, but this was actually what Samsung intended.

By the way, for questions like this, where there isn't really a bug report, I recommend posting in the [forums](http://forum.starling-framework.org/forum/feathers). It's better for discussion.

**Comment by chichilatte** [comment]
Thanks Josh that's great to know. From my research today it seems in native Android apps you can get the true screen density using `getResources().getDisplayMetrics().xdpi` in java (but again it's [potentially inaccurate](https://stackoverflow.com/questions/3166501/getting-the-screen-density-programmatically-in-android)). So if I was determined to get the same physical size across devices I could write an ANE to get the true dpi. Not worth the bother surely.

+I made this an issue just because I thought it would be an improvement if the [docs](http://feathersui.com/api-reference/feathers/utils/ScreenDensityScaleFactorManager.html) could communicate the concept of physical size, which I think is crucial to getting your head around this complicated stuff! Given that, the docs are already fabulous :)

**Comment by joshtynjala** [comment]
I'll try to clarify the docs a bit.
