### ISSUE TITLE
TextFieldTextRenderer doesn't measure correctly when Starling.contentFactor is different than 1

### ISSUE THREAD

**Issue by generagames** [BowlerHatLLC/feathers#1253]
When working with multi-resolution devices and Starling's contentScaleFactor differs from 1, pixel calculations performed at TextFieldTextRenderer.measure() function results in decimal values that seems to be truncated in later steps, loosing the necessary remaining pixel to properly display the text.

***TextFieldTextRenderer.as*** (lines from 1476 to 1550)
```
protected function measure(result:Point = null):Point
{
[...]
if(needsHeight)
{
	newHeight = (this.textField.height / scaleFactor) - gutterDimensionsOffset;
[...]
```

The error is fixed just being generous with the newHeight:

	newHeight = Math.ceil(this.textField.height / scaleFactor) - gutterDimensionsOffset;

Here is the result in my project.

![textfieldtextrenderer_measure_error](https://cloud.githubusercontent.com/assets/12172835/11471445/e4e413b2-9765-11e5-8000-c20a74048024.jpg)

I hope it helps! Thank you very much for your work Josh!

**Comment by joshtynjala** [comment]
Thank you. I can reproduce using the following code for the text renderer:

	var text:TextFieldTextRenderer = new TextFieldTextRenderer();
	text.text = "I am the very model of a modern major general";
	text.textFormat = new TextFormat("TestFont", 25);
	text.embedFonts = true;
	text.width = 210;
	text.wordWrap = true;
	this.addChild(text);

I used a stage size of 460x284 and a screen size of 800x480, which resulted in a content scale factor of 1.7391304347826086.

I embedded is Arial.tff with a different name to avoid potential conflicts with the device font:

	[Embed(source="Arial.ttf",fontFamily="TestFont",fontWeight="normal",mimeType="application/x-font",embedAsCFF="false")]
	protected static const EMBEDDED_FONT:Class;

It does not reproduce using these settings if the font is not embedded because I think TextField renders a little bit different with device fonts. It looks like it has a stronger weight. It may be possible to reproduce with a device font, but it would require some tweaks to find the right TextField width and things.

**Comment by generagames** [comment]
Thank you Josh for your attention, I'm glad to help :)
