### ISSUE TITLE
PopUpManager wrong centerize on resize

### ISSUE THREAD

**Issue by mynameismisha** [BowlerHatLLC/feathers#1259]
PopUpManager wrongly centerize the popup. When resize event is handled, the stage has old width and height values. You can see it, if to quickly change the window size, of if to maximize the window.

**Comment by joshtynjala** [comment]
When you listen for the native stage Event.RESIZE in your startup class, you can give it a higher priority to be sure that it is processed before Starling dispatches its own resize event. This is how I do it:

    nativeStage.addEventListener(Event.RESIZE, nativeStage_resizeHandler, false, int.MAX_VALUE, true);

That will fix this issue.

**Comment by mynameismisha** [comment]
Hm.. How adding listener to the native stage resize event will fix the problem with PopUpManager?
Or maybe i described the problem not clear.
I use PopUpManager.addPopUp(_popup, true, true). The popup appears on the center of the window and the overlay is on the hole window. But if to maximize the window - the popup won't change position and the overlay won't change size. I investigated a little and found that in handler method stage_resizeHandler of the DefaultPopUpManager stage has old width and height values.

**Comment by joshtynjala** [comment]
I understood what you meant. The stage has old width and height values because Starling's event listener is handling the native stage's Event.RESIZE first, before your own resize event can actually change the dimensions of the stage. Starling's listener dispatches Event.RESIZE to the Starling stage, even if you have not yet had the opportunity to resize the Starling stage in your own listener. By giving your listener a higher priority, you handle the event first, and the stage will have the correct dimensions in the event listener.

**Comment by mynameismisha** [comment]
Ok, I got it. Thanks for the explanations. All works fine now :)
