### ISSUE TITLE
PickerList popup's select behavior

### ISSUE THREAD

**Issue by teotigraphix** [BowlerHatLLC/feathers#1269]
Question, when a PickerList shows it's list popup, is there any way to get the List to show the selected item before the list is destroyed?

I am talking for a spilt second so the user knows they actually selected the item. Right now for some reason, I select the item and I don't have any visual queues that the item selected was exactly what I tapped.

Not saying this is a bug but is this the intended behavior? (select, list destroyed before the list shows the new selection)

**Comment by joshtynjala** [comment]
Are you targeting desktop or mobile? Which IPopUpContentManager are you using?

**Comment by teotigraphix** [comment]
It's mobile and the content manager in phone mode is VerticalCenteredPopUpContentManager.

I'm basically using the exact same code from the MetalWorksMobileTheme.

**Comment by joshtynjala** [comment]
So part of what's happening here is that the item renderer down state is delayed by about 250ms. This keeps the item renderer from changing to the down state right away when you touch the list because you might simply want to scroll the list. That flickering to the down state on TouchPhase.BEGAN and then back to the up state when the scrolling starts doesn't look nice.

Then, the list closes before it can switch to a selected state. The VerticalCenteredPopUpContentManager doesn't have any kind of closing animation, so the List is removed from the display list immediately.

In desktop themes, the item renderer's useStateDelayTimer property is usually set to false so that the down state can appear immediately, since scrolling works differently on desktop. If your list doesn't need to scroll, this could work on mobile too.

Another option would be to modify the VerticalCenteredPopUpContentManager to add in some kind of delay before removal or maybe an animation, like fading out the alpha value.

Finally, you could use the BottomDrawerPopUpContentManager and SpinnerList, which is the new default in Feathers 2.3. This option acts more like iOS with a drawer that opens on the bottom of the stage. It doesn't close immediately when you select an item. Instead, you either need to tap a button or touch outside of the drawer's bounds to close it.

**Comment by teotigraphix** [comment]
Ok Kewl, I will note this. For now I just changed the logic to use CalloutPopUpContentManager for now. Seems to work fine for what I need until I have more time to investigate. At least the user can instantly see the selection in context since the List is not taking up the whole screen.

BTW, I was wondering when you use that full List manager that occludes the whole screen, how can a user cancel a list selection? I was about to change this anyway because other then pressing back, there is no screen to tap.

**Comment by joshtynjala** [comment]
VerticalCenteredPopUpContentManager lets you specify some margins around the edges of the stage. Tapping the margin will close the list.

You can also tap the item that is already selected.

**Comment by teotigraphix** [comment]
Ah yeah, adjusting the margins is something I didn't think about but obvious. Selecting the item in my list wouldn't be an option since it's 30 items long or more.

**Comment by joshtynjala** [comment]
VerticalCenteredPopUpContentManager is inspired by Android, so I'm sure the engineers at Google designed it with the idea that the back button would always be available and the obvious choice. Without a system-wide back button on iOS, I'll admit that it's not as friendly.

**Comment by teotigraphix** [comment]
Yeah I was thinking the same thing but with Android's immersive mode, the back button isn't there until you swipe up.
