### ISSUE TITLE
TextInput forces Starling 2.0 to render every frame even with skipUnchangedFrames

### ISSUE THREAD

**Issue by serjek** [BowlerHatLLC/feathers#1340]
Having TextInput on display list even out of stage (for example in list itemRenderer being scrolled out of view) makes additional children spawn on native stage and this forces Starling.mustAlwaysRender to return true. This in turn forces render every frame even with skipUnchangedFrames turned on, despite the fact the frames on stage are not actually changing.

**Comment by joshtynjala** [comment]
This is a known issue, but I don't know how to solve it. The children must be on the native stage to for the text editor to measure properly.

**Comment by serjek** [comment]
Perhaps removing children from native stage when textinput is not changing would solve the problem. Or request Starling to ignore native stage children that are invisible in Starling.mustAlwaysRender. Or just leave as it is: it's not a critical bug after all.

**Comment by joshtynjala** [comment]
Yeah, I also thought of asking Daniel to make Starling ignore children on the native stage with visible set to false. That seems like the best approach.

Some text editors need a TextField on the native stage for accurate measurement because apparently TextField doesn't always report the right dimensions when it isn't on the stage. So it's not simply a matter of removing it when the TextInput doesn't have focus. Temporarily adding and removing the TextField during measurement would work, but it may cause many flash.events.Event instances to be created and dispatched. That will result in too much extra garbage collection.

**Comment by PrimaryFeather** [comment]
My latest commit should fix that, Josh! I'm now recursively checking if there's any visible content on the native stage.

**Comment by joshtynjala** [comment]
Thanks, Daniel! I added a question on the commit.
