### ISSUE TITLE
VideoPlayer and skipUnchagedFrames - Feathers 3.0

### ISSUE THREAD

**Issue by timoisalive** [BowlerHatLLC/feathers#1348]
So the video texture needs to be updated even when `starling.skipUnchangedFrames` is switched on. Is there a plan on automating this for the Feathers VideoPlayer, or is it something users should do manually? If latter, what's your suggestion on how to do it? Switch `starling.skipUnchangedFrames` off for the time the video plays, or call `starling.setRequiresRedraw()` in each frame?

**Comment by joshtynjala** [comment]
My initial feeling is that if automating it in VideoPlayer were the correct approach, Daniel would have done it at a lower level, in Starling. However,  thinking on it more, I think that VideoPlayer has more detailed knowledge of the current playback state than a raw video texture. Perhaps VideoPlayer should indeed call setRequiresRedraw() while it is playing. I already have an enterFrame listener to track the current time when the video is playing, so that would be an appropriate place to do it.

**Comment by joshtynjala** [comment]
Okay, so it looks like the VideoPlayer cannot call setRequiresRedraw() automatically. It provides the texture, but the ImageLoader or Image that displays the texture is controlled by you, so it doesn't know where to call that function. It could change skipUnchangedFrames automatically instead, but that's a little too global for my tastes. If multiple VideoPlayers start playing, there's a non-trivial potential for their states to get out of sync.

That means it is your responsibility to tell Starling that it needs to update. It's worth noting that if you are using ImageLoader, you don't have access to its internal Image, so you cannot call setRequiresRedraw() on it. That means that you probably need to change skipUnchangedFrames to false during playback.

**Comment by timoisalive** [comment]
Ok, thanks Josh for looking into it! 👍
