### ISSUE TITLE
How does scale9Grid work?

### ISSUE THREAD

**Issue by brean** [BowlerHatLLC/feathers#1395]
Hi,

I looked into the existing themes and noticed that the [description for the scale grid](http://feathersui.com/help/scale9-image.html) does not match the values. Is the documentation outdated? 

For eample, in the AeonDesktopTheme the default Button has a size of 22x44 pixel. When I manually create the grid I get 7x7 as starting point with a width of 8 px and a height of 29 px. In the [BaseAeonDesktopTheme](https://github.com/BowlerHatLLC/feathers/blob/master/themes/AeonDesktopTheme/source/feathers/themes/BaseAeonDesktopTheme.as) the BUTTON_SCALE_9_GRID has 5, 5, 1, 7 as values, so way off from the 7, 7, 8, 29 I would expect.

**Comment by joshtynjala** [comment]
The grid is based on the dimensions of the texture. The default dimensions of a component, like a Button, may not necessarily match the texture dimensions. In fact, the component will usually be larger because the texture will be made as small as possible to optimize memory.

For future reference, a better place to post a question like this is in [the forum](http://forum.starling-framework.org/forum/feathers). It'll give others a chance to answer.
