### ISSUE TITLE
Interface for ListCollection

### ISSUE THREAD

**Issue by ze0nni** [BowlerHatLLC/feathers#1399]
I'd love to make their ListCollection its implementation without having to inherit from ListCollection.
My models use mx.collections classes and that would associate them with the feathers have to write really bad code.

**Comment by joshtynjala** [comment]
http://feathersui.com/api-reference/feathers/data/IListCollectionDataDescriptor.html

http://feathersui.com/api-reference/feathers/data/ListCollection.html#dataDescriptor

**Comment by joshtynjala** [comment]
You don't need to subclass. You can create a new data descriptor for your data format.

**Comment by ze0nni** [comment]
Right, but  mx.collections.IList is implements IEventDispather and notify abount adding/removing/replaceing items, like feathers ListCollection.

If I implements IListCollectionDataDescriptor for mx.IList I can not notify ListCollection about changes into IList

**Comment by joshtynjala** [comment]
A hypothetical IListCollection interface would expect implementations to extend starling.events.EventDispatcher. This is not compatible with IEventDispatcher, so you'd need to wrap your Flex collections in something else. Seems messy, but I guess it's allows you to manipulate the Flex collection directly instead of going through ListCollection, which is your goal.

An IListCollection interface is something that I can do, but there are many other things that would have a higher priority, so I can't promise anything soon. Maybe if I get a moment here or there. It would help if you could get some more votes from the community on this issue.

**Comment by ze0nni** [comment]
Now I have bridge-class between mx IList and feathers ListCollection, it is work good, but I have worried about this solution.

If in the future I can do it with decorator around mx.IList it will great.

Thanks you!
