### ISSUE TITLE
ScrollContainer: Issues with last horizontal page

### ISSUE THREAD

**Issue by kevinfoley** [BowlerHatLLC/feathers#1410]
The ScrollContainer has several issues with calculating the number of pages and the size of the last page:

- If the rightmost display object in the ScrollContainer is center-aligned instead of left-aligned, the ScrollContainer will miscalculate the number of horizontal pages. For example, the pageWidth is set to the stage width. A graphic with width less than the stage width is centered on the third page (`graphic.alignPivot("center", "top"); graphic.x = stage.stageWidth * 2.5`). The ScrollContainer incorrectly calculates the number of horizontal pages as 4 

- The last horizontal page ignores the declared page width and will only size itself to the width of its contents. If the page width is the stage width, the width of the contents of the last page are less than the stage width, and we scroll to the last page, we can still see some of the second-to-last page

**Comment by joshtynjala** [comment]
1. Yes, it looks like the default "layout" used by LayoutGroup (which is then used by ScrollContainer too) does not account for pivotX and pivotY. I'll get that fixed.

2. This is actually by design. The layouts themselves don't really know if they're in a scrolling container or not, let alone if it snaps to pages. If the layout needs every page to fill the full width of the container, it needs to do it manually. TiledRowsLayout and TiledColumnsLayout support this behavior when their paging properties are enabled. They will add extra space at the end to fill a full page. Other built-in layouts don't have anything like that by default. It might be easy to subclass and add that, though.

**Comment by kevinfoley** [comment]
Ok, thanks!
