### ISSUE TITLE
TextInput.promptFactory: BitmapFontTextRenderer.textFormat overwritten by theme.

### ISSUE THREAD

**Issue by tconkling** [BowlerHatLLC/feathers#1412]
I'm having an issue with `TextInput.promptFactory` where my prompt's text format is being overwritten after creation. 

I'm creating a TextInput and assigning it a promptFactory:

```actionscript
    public static function createInputText (prompt :String, isPassword :Boolean, parent :Sprite) :TextInput {
        var textInput :TextInput = new TextInput();

        // add the TextInput to the sprite before changing its properties, or they'll be overridden
        // by feathers
        parent.addChild(textInput);

        textInput.promptFactory = function () :ITextRenderer {
            var tr :BitmapFontTextRenderer = new BitmapFontTextRenderer();
            tr.textFormat = new BitmapFontTextFormat(FONT_UI_LARGE, 10, 0x666666);
            return tr;
        };
        textInput.promptProperties = null;
        textInput.prompt = prompt;
        textInput.width = 150;
        textInput.height = 22;
        textInput.displayAsPassword = isPassword;
        textInput.textEditorProperties.fontFamily = "Helvetica";
        textInput.textEditorProperties.fontSize = 12;
        textInput.textEditorProperties.color = 0x0;

        return textInput;
    }
```

My promptFactory creates a `BitmapFontTextRenderer`, assigns it a `textFormat`, and returns it. However, when the `BitmapFontTextRenderer` is later added to the stage by its TextInput parent, the theme I'm using (`BaseMinimalMobileTheme`) overwrites that textFormat in the `BaseMinimalMobileTheme.setTextInputPromptStyles` function.

Is this the intended behavior? (This was not happening when I was using Feathers 2.) What's the proper way to get that textFormat to stick?

**Comment by joshtynjala** [comment]
This is the intended behavior, and it also behaved this way in Feathers 2. However, the theme may have done some things differently that could explain why you're seeing different behavior. The old theme probably used textInput.promptProperties before, and it no longer does (because I now consider those properties objects a poor design decision, and I avoid them completely). You set input.promptProperties to null, but the theme doesn't use that object anymore.

You have two options (and these are the recommended practice for styling any sub-component):

1. Set the text renderer's style provider to null in the promptFactory. This will tell it not to use the theme at all. You can immediately set properties and be sure that the theme won't replace them:

    ``` as3
    var tr :BitmapFontTextRenderer = new BitmapFontTextRenderer();
    tr.styleProvider = null;
    tr.textFormat = new BitmapFontTextFormat(FONT_UI_LARGE, 10, 0x666666);
    ```
    This works especially well for text renderers because you usually want to fully replace their default font styles. For more complex components where you want to keep some of the theme's defaults, the second option usually works better.
1. You can use an AddOnFunctionStyleProvider to ensure that custom styles don't get set until after the theme has set its defaults:

    ``` as3
    var tr :BitmapFontTextRenderer = new BitmapFontTextRenderer();
    tr.styleProvider = new AddOnFunctionStyleProvider(tr.styleProvider, function(tr:BitmapFontTextRenderer):void
    {
        tr.textFormat = new BitmapFontTextFormat(FONT_UI_LARGE, 10, 0x666666);
    };
    ```

The function that you pass to AddOnFunctionStyleProvider is called after the theme's code, so it's similar to your old trick of adding the component to the stage before changing styles.

**Comment by tconkling** [comment]
Thanks!
