### ISSUE TITLE
ImageLoader takes too long to calculate its size correctly

### ISSUE THREAD

**Issue by kevinfoley** [BowlerHatLLC/feathers#1437]
ImageLoader takes several frames to calculate its own size correctly after the window resizes. This is most readily apparent in a desktop application with resizable window, by maximizing and un-maximizing the window. Calling validate() on the ImageLoader or its parent has no effect on the calculated size.

This is a problem when the size of other controls is calculated based on the size of the ImageLoader. For example, if the height of some control is `stage.stageHeight - imageLoader.height - _gap - _padding`, the control will be sized incorrectly after the user maximizes or un-maximizes the window.

        private function onAddedToStage():void {
			var verticalLayout:VerticalLayout = new VerticalLayout();
			this.layout = verticalLayout;
			
			imageLoader = new ImageLoader();
			imageLoader.source = "http://feathersui.com/images/feathers-ui-three-iphones.png";
			imageLoader.maintainAspectRatio = true;
			addChild(imageLoader);
			
			var vld:VerticalLayoutData = new VerticalLayoutData(50);
			imageLoader.layoutData = vld;
			
			Starling.current.nativeStage.addEventListener(Event.RESIZE, onResize);
		}
		
		private function onResize(e:*):void {
			validate();
			imageLoader.validate();
			validate();
			imageLoader.validate();
			traceImageLoaderSize(); //outputs wrong size
			Starling.juggler.delayCall(traceImageLoaderSize, .02); //outputs correct size
		}
		
		private function traceImageLoaderSize():void {
			trace(imageLoader.width, imageLoader.height);
		}

**Comment by joshtynjala** [comment]
The Starling stage may not have been resized yet when your nativeStage onResize listener is called. Feathers listens to the resize event from the Starling stage, and order/priority of the listeners that end up resizing the Starling stage can mean that your listener is called first. If that's the case, nothing will be invalid in your listener.

Additionally, it may not be the ImageLoader or the parent of the ImageLoader that is invalid yet. I don't know the hierarchy of your display list, but something closer to the stage may be what's invalid at that point. Until it validates, the ImageLoader won't be affected yet.

Finally, when the stage resizes, the Stage 3D back buffer needs to resize. This is expensive, and I think it can take multiple frames sometimes. Maybe even lose context.

Now, maybe I'm missing something important because I haven't tried to run your code yet. I'll be back to work on Monday, and I can look more closely then.

**Comment by kevinfoley** [comment]
> The Starling stage may not have been resized yet when your nativeStage onResize listener is called. 
I've verified that's not the problem by tracing the Starling stage size when the resize listener is called. In the example above, the ImageLoader is added directly to a PanelScreen, so when I just call `validate()` by itself, it validates the entire screen. Every other type of Feathers control seems to validate and calculate its size correctly at this time, so this appears to be an issue specific to ImageLoader.

**Comment by joshtynjala** [comment]
I tried using the code that you posted in a simple project, but I'm seeing the same width and height values in the console both before and after the delayed call. The ImageLoader appears to be resizing immediately in my project.

Are you sure that your PanelScreen was actually resized before onResize is called? Like I said, you may be calling validate() on something that hasn't been invalidated yet. If something higher up in the display list, like a StackScreenNavigator, was resized when the stage resized, the new dimensions may not have been passed down to the PanelScreen yet.

**Comment by kevinfoley** [comment]
Sorry for getting back to you slowly. I've been busy but will try to look into this more today.

**Comment by kevinfoley** [comment]
You're right, the parent StackScreenNavigator hadn't been invalidated yet. I was able to fix the issue by calling

    (parent as FeathersControl).invalidate();
    (parent as FeathersControl).validate();
    this.invalidate();
    this.validate();
