### ISSUE TITLE
DateTimeSpinner.scrollToDate  - a small issue 

### ISSUE THREAD

**Issue by LicVit** [BowlerHatLLC/feathers#1445]
Way to reproduce:

**// 1) Create DateTimeSpinner instance**

var _dateSpinner:DateTimeSpinner = new DateTimeSpinner()
_dateSpinner.editingMode = DateTimeMode.DATE
this.addChild(_dateSpinner);

**// 2) Scroll to some random date with animationDuration == 0**

_dateSpinner.scrollToDate(new Date(2111,11,31), 0)

**// 3) Read "value" property after ---> it will return the current date (but the component will display the date properly)**

Starling.juggler.delayCall(function(e:Event = null):void{
trace("DateTimeSpinner :", _dateSpinner.value);
},2)

p.s. with _dateSpinner.value = new Date(2111,11,31) works properly

**Comment by joshtynjala** [comment]
Sorry for the delayed response. I've been busy with some things related to styling recently.

This is actually by design. scrollToDate() is strictly meant for animation, and even with a duration of 0, it won't change the scroll position until the next time that the DateTimeSpinner validates. If you call validate() manually, the correct date should be reflected.

``` actionscript
_dateSpinner.scrollToDate(new Date(2111,11,31), 0)
_dateSpinner.validate();
```

I'll make a note of that in the API reference, if it isn't there already.
