### ISSUE TITLE
StageTextTextEditor: Losing focus when I exit the App

### ISSUE THREAD

**Issue by GV3** [BowlerHatLLC/feathers#1458]
Hi Josh, I don't know if this is a natural behavior, but when I exit an App the StageTextTextEditor will lose focus, even when maintaining the touch focus:

`_textInput.textEditorProperties.maintainTouchFocus = true;`

Is there a way to through the Focus Manager of Feathers to Avoid this?

If not, what would you recommend?

**Comment by joshtynjala** [comment]
I'm not sure that I understand. If you exit the app, it won't exist anymore, right? Or do you mean something else, like when the app goes into the background?

**Comment by GV3** [comment]
Yes, I mean switching to another App but without closing this App.

Then when I return, I expect the App to have kept the focus on the same TextInput control

**Comment by joshtynjala** [comment]
Since the focus change isn't triggered by a touch, maintainTouchFocus doesn't apply. Most likely, you'll need to restore focus manually when the NativeApplication or nativeStage dispatches Event.ACTIVATE. If you need to know which TextInput had focus before going into the background, you can check on Event.DEACTIVATE.
