### ISSUE TITLE
TapToTrigger: double tap

### ISSUE THREAD

**Issue by teotigraphix** [BowlerHatLLC/feathers#1464]
I use this so much with custom item renderers. Seeing we have the LongPress, double tap would complete the features.

---

This next part was moved to #1465 by @joshtynjala

~~One other question, how about exposing the core down, move, up events as well? Could maybe have an enabled so they are not being dispatched if you don't want them?~~

~~If you could add this stuff to the class OR make a different class if you don't want to foul TapToTrigger up, this would remove so much boiler plate code and error prone copy and paste for simple touch handling.~~

~~We would need the TouchEvent(for core touch events) in the data property dispatched out of the class.~~

**Comment by joshtynjala** [comment]
> how about exposing the core down, move, up events as well?

What kind of different API are you expecting here? I'm not sure what would be simpler than TouchEvent.TOUCH...

**Comment by teotigraphix** [comment]
Well, I may be missing something but;

If I want to listen for TouchEvent, I would have to write my own handler. Using TapToTrigger, you already track the touchPointID.

So within target_touchHandler(), dispatching the correct touch event that is NOT actually a touch but based on the logic of that handler is what I am talking about.

Take for example, the Button's touch handler, you would dispatch these events where you call change state.

I am just asking for an encapsulation of the touch handler that dispatches events in a concrete place based on the state of the touccPointID that I would not have to track.

Since you are already doing that in TapToTrigger, I figured it's the natural place to encapsulate those "state changes".

Maybe I am asking for kind of state events then, not so much "touch" events. I like using your stuff because you know exactly what the framework is doing, when I write my own handlers, sometimes I feel I may be missing something.

**Comment by joshtynjala** [comment]
Moved the touch states part into #1465 so that they're separate issues.

**Comment by GV3** [comment]
Hi, guys!

I'm a devoted user of the TapToTrigger class myself and believe the double tap would be a great addition to it!

Also, I remembered that I had the following request/bug-report regarding the TapToTrigger:

It registers MORE than just a Tap :) 

It's more a TouchDown that dispatches on TouchUp. 

Let me explain myself, a tap by definition is a quick touch of a point of the screen. If you leave the finger too long is not a tap, if you remove the finger from a different rather far location is not a tap, and if you quickly swipe left and right and release at the same point, it should also not count as a tap.

While working with the TapToTrigger, I noticed that it would dispatch even if the user presses for a long time or if the release position is very distant.

In my opinion, the TapToTrigger class should be extended to accept properties such as tapDuration, tapDistance, and slop (in case the finger travelled to far on the screen before returning to the original touch point for the release)

Now, WHY would this be important? Or why is the current Tap not enough?

Because most of the ItemRenderers today are designed to slide left and right; because the acceptance of the 3D touch is slow but inevitable; and because it's just the right way of solving that the scroller doesn't select an item when scrolling. (from within the ItemRenderer and not on the scroller itself).

What do you think? Any chance of adding this extra functionality to the TapToTrigger?  :)

**Comment by joshtynjala** [comment]
TapToTrigger is designed to work similarly to MouseEvent.CLICK. As long as the touch begins and ends on the target, it's considered a tap/click. I'm not changing years of precedence.

You're welcome to design your own version, though! That's the great part about this utility, it's completely optional!

**Comment by teotigraphix** [comment]
Not really related but, with years of experience with the Flex framework, I make these types of feature request to solidify Feathers. 

Flex's sub-classing and copy/paste drove me insane.

Having a reusable library IE Feathers in ONE place is gold. The more experienced make weird requests but it always benefits other developers down the line with time savings. :)

**Comment by GV3** [comment]
This feature request was never meant to change the years of precedence.

The idea was to allow additional properties in case the developer would require the Tap to have the restriction of tapDuration, tapDistance, and slop.

I guess I'm not the only Feathers developer that is requested to build slideable ItemRenderers.

And as @teotigraphix says, having a reusable library with all the functionality in one place and working like a swiss clock is beneficial for everyone. 

@teotigraphix :

>  you know exactly what the framework is doing, when I write my own handlers, sometimes I feel I may be missing something.

I have exact the same feeling :)  
Don't want to break the swiss clock!

If you agree it's a feature that solves a common problem/need of Feather's dev, you could just list it as an enhancement without committing to a release version, and just to see how many votes or attention it gets.

**Comment by joshtynjala** [comment]
Feel free to open a separate issue for that! Each issue should focus on one thing. Otherwise, it's a big mess of multi-threaded conversation. Like this one is becoming. 😉

**Comment by teotigraphix** [comment]
Nice Josh. :)
