### ISSUE TITLE
Using [Deprecated] meta in comments

### ISSUE THREAD

**Issue by marpies** [BowlerHatLLC/feathers#1471]
I just noticed there is [Deprecated] meta tag available in AS3, I had no idea! It's also visually supported by IntelliJ as it ~~crosses out~~ the API marked with this meta. Is there a reason why you are not using this meta in your comments?

**Comment by GV3** [comment]
@marpies, Is more than just the crossed out text, the [Deprecated] metatag will produce compiling warnings, what I find incredibly useful! 

Plus, you can add an extra text with info about how to deal with the deprecated object. 

PS: I know... this should go in the forums... but hey! at least I didn't started it this time ;)

**Comment by joshtynjala** [comment]
> Is there a reason why you are not using this meta in your comments?

Maybe things are better now, but the last time I tried using [Deprecated] metadata, Flash Builder would always show the compiler warning, even if the project wasn't actually using the API that's been deprecated. That made [Deprecated] metadata almost useless, in my opinion. A warning for something that you haven't done, that also can't be fixed without something drastic like modifying the library's source code, is super annoying.

I'll investigate again. It could be that this was behavior that only affected ASC 1.0. I also think it only happened if you were using the library's source code, and not if you added the SWC. Unfortunately, the Feathers SDK still uses ASC 1.0, but since Feathers is built as a SWC in the SDK, that might be okay.
