### ISSUE TITLE
VerticalLayout: The list jumps when scrolling up using  sticky headers.

### ISSUE THREAD

**Issue by GV3** [BowlerHatLLC/feathers#1478]
Hi Josh, 

I've found the following BUG in the vertical layout.

Steps to reproduce:
- Create a large GroupedList with sticky headers, say 100 groups. (I have a random amount of children in each group, but I believe it's not relevant to the bug)
- Scroll the list to the group 80 and THEN add it to the display list
- Now scroll upwards, direction group 79
- Note how every time an item renderer appears on the screen from the top, the verticalScroll position jumps (In my case it seems that it jumps the amount of pixels of the headers)

If I add the same list to the stage when displaying the group index 0 and scroll down, I won't see the same jumps on my way up. 

But if I start somewhere in the bottom and scroll up, the list will constantly jump in what seems to be the size of the sticky headers.

**Comment by joshtynjala** [comment]
When an item renderer is created, and the virtualized layout starts using the real height instead of an estimated height, it automatically corrects for the difference. It sounds like sticky headers need to do it slightly differently because they start to be shown from a different position. I'll take a look!

**Comment by GV3** [comment]
Great, thanks Josh!

**Comment by GV3** [comment]
I decided to try a different approach and scrolling now works like a CHARM, I'll share it here in case someone else is dealing with the same issue.

Spoiler alert: It's not a bug fix, is more of a hack.

I've completely replaced all GroupedLists with regular List using the factoryIDFunction to recognize and instantiate Headers.

In the case a GroupList was displaying stickyHeaders I just made sure to update the .headerIndices property of the VerticalLayout of the regular List, and voila! 

My GrupeLists never scrolled as fast and as good as now.

I'm not sure if this approach could serve to replace all GroupLists, but it certainly solved and the needs I had and this with a substantial performance improvement.

**Comment by joshtynjala** [comment]
Are you setting hasVariableItemDimensions to true or false on the regular List's VerticalLayout? GroupedList sets it to true by default, and List normally sets it to false by default. If it's false, and the headers are forced to be the same height as regular items, the layout can optimize with some simple math instead of looping through the items one by one. Just curious if that might be why you're seeing better performance with List.

**Comment by GV3** [comment]
hasVariableItemDimensions is set to true

The performance is definitely better, but most importantly the bug described above is gone. If I add a large list (1000 items) to the stage while displaying an item in the center (let's say index 500) and start scrolling towards index 0 the list will behave as expected without any funny jumps everytime the headers appear
