### ISSUE TITLE
Setting custom fontStyles on Button in Theme

### ISSUE THREAD

**Issue by teotigraphix** [BowlerHatLLC/feathers#1516]
I am having a problem here with fontStyles.

I have a Theme I have been using for over a year and it sets the defaultStyleProvider for a TextBlockTextRenderer using ElementFormat.

What I don't understand is the default Buttons are styled with that but if I try to set fontStyles in a Class override;

```
        button.fontStyles = new TextFormat("Sansation", 12, 0x333333);
        button.fontStyles.bold = true;
        button.fontStyles.verticalAlign = Align.TOP;
```

They don't get applied unless I remove the TextBlockTextRenderer's defaultStyleProvider setting.

Is there a way to set fontStyles to override this in a Theme for a subclass of a Button?

EDIT:

```
theme.getStyleProviderForClass(ChannelButton).defaultStyleFunction = set_ChannelButton_Styles;

...

    private function set_ChannelButton_Styles(button:ChannelButton):void
    {
        //     channel - select - button - up - skin
        var upSkin:Image = new Image(atlas.getTexture("channel-select-button-up-skin"));

.....
        
        button.padding = 0;
        
        button.fontStyles = new TextFormat("Sansation", 12, 0x333333);
        button.fontStyles.bold = true;
        button.fontStyles.verticalAlign = Align.TOP;
        
        button.selectedFontStyles = new TextFormat("Sansation", 12, Theme.COLOR_WHITE_CREAM);
        button.selectedFontStyles.bold = true;
        button.selectedFontStyles.verticalAlign = Align.TOP;
    }
```

**Comment by teotigraphix** [comment]
I am putting this as an issue because I would expect this to work as a user, since fontStyles are directly tied to a button and this "should" work in my mind. 

If it doesn't I understand but maybe it should. :)

**Comment by joshtynjala** [comment]
The properties that accept ElementFormat on the text renderer always take precedence over the fontStyles that are passed to the text renderer from the parent component. Part of that is for backwards compatibility. I didn't want to break all of the existing code that could only set the ElementFormat on the text renderer when I simplifiedcode the themes to use fontStyles. However, ElementFormat is also considered more advanced than starling.text.TextFormat because it's lower-level and hat more options, so it should be more important when someone chooses to use it.

**Comment by teotigraphix** [comment]
Ok, fair enough, I was being lazy but since I am established in my theme as using ElementFormat, I will just keep doing what I have been doing. Ah it was much less code with TextFormat. haha!
