### ISSUE TITLE
GroupedList scrollToDisplayIndex() header position

### ISSUE THREAD

**Issue by harry248** [BowlerHatLLC/feathers#1519]
Manually scrolling to a group index via scrollToDisplayIndex() the corresponding header is being vertically centered within the viewport. This behaviour may be correct for regular list items but I think headers should be aligned to the top. Unfortunately I wasn't able to achieve that easily. I had to mix scrollToDisplayIndex(), headerDataToHeaderRenderer() and scrollToPosition() and some validate() calls in between to get it to work but that's just ugly. It would be nice if the alignment could be changed for headers or if the alignment could be passed to scrollToDisplayIndex().

**Comment by joshtynjala** [comment]
The alignment of scrollToDisplayIndex() can be controlled with a property on the layout. In the case of VerticalLayout, it's [scrollPositionVerticalAlign](https://feathersui.com/api-reference/feathers/layout/VerticalLayout.html#scrollPositionVerticalAlign).

The component isn't really able to control the alignment because the layout isn't necessarily vertical only. There's a different property with different values on HorizontalLayout, and other layouts could be completely different.

I guess maybe I could add another property on VerticalLayout similar to scrollPositionVerticalAlign for headers only. It knows about the header indices, so it can have different behavior for them.

**Comment by harry248** [comment]
I wasn't aware of the scrollPositionVerticalAlign property. It is exactly what I was looking for. Thanks for pointing that out!
