### ISSUE TITLE
AIR 24 'fonts' folder conflicting with themes 'fonts'

### ISSUE THREAD

**Issue by teotigraphix** [BowlerHatLLC/feathers#1520]
See this;

http://forum.starling-framework.org/topic/air-24-stagetext-error-on-android?replies=3#post-100642

I may be wrong but is this going to be a problem for Feathers and you using the 'fonts' directory for your themes?

I know it killed 4 hours of my time and I had to change the directory name.

**Comment by joshtynjala** [comment]
I've been testing with AIR 24, and I haven't encountered this issue yet. It may depend on additional factors. I'll double check on an Android device when I get back to work after the holidays.

**Comment by teotigraphix** [comment]
It was only happening in NON debug run, so a normal Run from the IDE. If I ran the app in debug on the device I didn't get the Error when using a popup with a TextInput. Rather strange but it drove me nuts. :)

**Comment by joshtynjala** [comment]
If you can make it happen with a simple project that contains only StageText, you should probably report a bug to Adobe.

**Comment by joshtynjala** [comment]
Try as I might, I wasn't able to reproduce. I used one of the Feathers example themes with a folder named fonts. I added another fonts folder to my project's source path. I included a fonts folder in the final APK. I guess there must be some additional factor.

Regardless, this is something that needs to be fixed in AIR. That sort of bug is too critical to simply workaround.
