### ISSUE TITLE
Autocomplete component bug in Android

### ISSUE THREAD

**Issue by svonnidmeg** [BowlerHatLLC/feathers#1548]
Recently discovered a strange behavior in Autocomplete component on Android. When appear the Android keyboard (from down) the app comes up (not in iOS) and the autocomplete dropdown goes up too (then it's loose above the screen and no options to see/tap).

On iOS works perfect (the app remain in original position already the keyboard goes up), the autocomplete dropdown is always visible and no issues.

Can anyone help me please?

Thx!,
Marc

**Comment by joshtynjala** [comment]
Hey, please try not to open an issue and post a thread in the forum with the same question. One place is enough. I'll see it in either place. It's usually best to start in the forums unless you're absolutely sure it's a Feathers bug because it gives more of the community a chance to help. People don't usually read through new Github issues the same way they do threads in a forum.

I'm going to close this issue and respond [in the forum](https://forum.starling-framework.org/topic/autocomplete-component-bug-in-android). If it turns out to be a Feathers bug, we can reopen this issue, but let's stick to the forum for now.
