### ISSUE TITLE
Gallery: outer List can incorrectly scroll when inner ScrollContainer from item renderer is dragged

### ISSUE THREAD

**Issue by denisgl777** [BowlerHatLLC/feathers#1566]
Suppose we increased the size of the picture and switched to the next one. Everything works well
If we return back, then an erroneous reaction is possible
The fact is that first the internal container must react to move the image
Instead of seeing the left edge of the image, we move on to the next image

**Comment by denisgl777** [comment]
The problem is not solved until the end
[https://ibb.co/dU15xa](url)
It is probably necessary to add a test condition
If the picture is larger than the screen, then the inner container must first be scrolled, and the external one must be locked
But at the moment an external container can be scrolled first

**Comment by joshtynjala** [comment]
The inner container always takes precedence. It's been like that for years. I'm not sure how you are making that happen, but I guess I'll investigate.

**Comment by denisgl777** [comment]
[https://ibb.co/hyk9OF](url)
[https://ibb.co/iGg5xa](url)
[https://ibb.co/cyNCca](url)
[https://ibb.co/grcOiF](url)

Maybe it will help you

**Comment by joshtynjala** [comment]
So I figured out how to reproduce this issue. If the outer container's scroll animation has not completed, and you begin a new touch, it will immediately resume dragging without passing the touch down to its children. This is by design, but when the animation is nearly complete, it can feel a bit like a bug. There may be a couple of milliseconds left on the Tween, but visually, it will look like it's completed. That's what you're encountering.

Interestingly, when I open up the native Photos app on iOS, I can reproduce this same issue! If you time it right, it is possible to make the outer view scroll when a photo is zoomed in.

With that in mind, I don't plan to make any changes.

I would suggest playing with the pageThrowDuration, if you're unhappy with this. You might find a value that works better for you. A longer value might make it more clear that the animation is still active. A shorter value might work too, since it will complete the animation faster than a user can touch the container. Also, if you haven't reset the scale on the photo when switching to a new page, like I did in commit 352518e9234acbd4d9cf662093c6b92f45985975, I highly suggest it.
