### ISSUE TITLE
Steps in ScreenNavigator example's build.xml implemented in VSCode tasks.json

### ISSUE THREAD

**Issue by charliesolomon** [BowlerHatLLC/feathers#1580]
I'm learning a lot from this repo, using VSCode with the awesome vscode-nextgenas extension.  I am going to start building up my tasks.json file to attempt the steps currently done in build.xml of the examples (I'm focusing on the ScreenNavigator example)... that is, I want tasks.json to not only build a SWF, but also the ios IPA, the android apk, and install them to devices.

Before I start, is there a good example elsewhere of these steps in a tasks.json?  

Would it make sense to fork this repo and make a VSCode compatible version?  Or just add the VSCode build files to this repo?

**Comment by joshtynjala** [comment]
It's not yet possible to package the IPA or APK with asconfigc (but I'd like to add that eventually), so your tasks.json will need additional tasks that run adt from the AIR SDK to package and install. I can't point to any examples of calling adt from tasks.json, but passing in command line options is pretty straightforward.

You could actually have tasks.json run the existing Ant tasks. It's meant to work with any build system.

In general, I try to avoid putting IDE specific project files in the repo. Since starting Feathers many years ago, I've used Flash Builder, IntelliJ IDEA, and now VSCode. I don't want to have a ton of project files to keep in sync, and I don't want to force my choice on users either.

**Comment by charliesolomon** [comment]
I appreciate the insight... I'll put my adt commands directly into tasks.json first.  Will also look into driving the existing Ant tasks, that's interesting!
