### ISSUE TITLE
PickerList button: skins gets stuck in DOWN state

### ISSUE THREAD

**Issue by kevinfoley** [BowlerHatLLC/feathers#1623]
If a PickerList button has an ImageSkin (either the `defaultSkin`, the `defaultIcon`, or both) with a color applied to the DOWN state, the color of the skin gets permanently stuck in the DOWN state the first time the user clicks on the button.

To test: in the *ComponentExplorer* project, open `BaseMetalWorksMobileTheme` and replace `setPickerListButtonStyles()` with this code:

    protected function setPickerListButtonStyles(button:Button):void
    {
        this.setButtonStyles(button);
			
        var skin:ImageSkin = new ImageSkin(itemRendererUpSkinTexture);
        skin.setColorForState(ButtonState.DOWN, 0x0000ff);
        skin.setColorForState(ButtonState.DISABLED, 0xcccccc);
        skin.width = this.controlSize;
        skin.height = this.controlSize;
        button.defaultSkin = skin;

        var icon:ImageSkin = new ImageSkin(this.pickerListButtonIconTexture);
        icon.selectedTexture = this.pickerListButtonSelectedIconTexture;
        icon.setColorForState(ButtonState.DOWN, 0x00ff00);
        icon.setTextureForState(ButtonState.DISABLED, this.pickerListButtonIconDisabledTexture);
        button.defaultIcon = icon;

        button.gap = Number.POSITIVE_INFINITY;
        button.minGap = this.gutterSize;
        button.iconPosition = RelativePosition.RIGHT;
    }

Run the project, go to the Picker List screen, and click on the Picker List. Observe that the button's skin changes color and does not change back.

I am not completely certain, but I believe this bug only affects the color. When you release your finger or the mouse from the button, the texture will return to its normal state, but the color of the texture does not return to normal.

**Comment by kevinfoley** [comment]
This issue doesn't happen if you explicitly set the `defaultColor`, so maybe the current behavior is intended, but I found it confusing. I think it would be nice if the `defaultColor` defaulted to `0xffffff`, since that is the default color of Starling Images (and Quads).

**Comment by joshtynjala** [comment]
I think that I was trying to make sure that setting the color property directly, like you would on a regular Image, was still possible on an ImageSkin. However, I think you're right that this is confusing if defaultColor doesn't behave similarly to defaultTexture with its default value.

I've changed the default value to 0xffffff. I've also added [Exclude] metadata for the color property to the ImageSkin class so that IDEs that support [Exclude] metadata will hide it from the completion list (unfortunately, IntelliJ IDEA ignores this metadata, last time I checked). I've also added a runtime error if you try to set the color property directly with the suggestion to use defaultColor or setColorForState() instead.
