### ISSUE TITLE
Two side slider

### ISSUE THREAD

**Issue by denisgl777** [BowlerHatLLC/feathers#1694]
Based on the old topics, I decided to implement two side sliders
https://gist.github.com/denisgl777/a5f9f6b730eae9e44fe31b48d4b5b101
Immediately after initializing the location of the elements, the incorrect
https://ibb.co/f1DDCc
I move the sliders and everything falls into place
https://ibb.co/ni9ydH
At what point do I need to re-check the location of the items?
This code worked well for feathers 2.0

**Comment by joshtynjala** [comment]
You should probably call validate() on the child components before you position them in layoutChildren(). Since they probably haven't validated yet, their width and height properties may be returning 0, which will affect your layout. By the time that you can interact with the slider, they will have validated automatically, so that's why the layout gets fixed.

**Comment by denisgl777** [comment]
Thank you Josh! The topic can be closed
