### ISSUE TITLE
Incorrect extraOSStatusBarPadding on iPhone X

### ISSUE THREAD

**Issue by subdan** [BowlerHatLLC/feathers#1704]
Status bar height on iPhone X is 44 pt. Could you set IOS_STATUS_BAR_HEIGHT value to 44 pt for iPhone X?

**Comment by subdan** [comment]
I test my app on iPhone X in Simulator.app.

**Comment by subdan** [comment]
Josh, it will be good to know iPhone X “Safe Area” size with Feathers to avoid issues like this:

![](https://useyourloaf.com/assets/images/2017/2017-09-17-001.png)

Could you add safe area property to Screen class?

**Comment by joshtynjala** [comment]
@subdan I recommend submitting a feature request to Adobe to have them expose the safe area in an AIR API.

I'm planning to submit my own feature request for the status bar height because it's getting too complicated to do this manually now that iPhone X has its own status bar height that's different from other iOS devices. If future devices have a notch, it's only going to get worse.

**Comment by joshtynjala** [comment]
Please vote!

[AIR-4198633: Property to get status bar height on mobile](https://tracker.adobe.com/#/view/AIR-4198633)

**Comment by subdan** [comment]
Voted! Thanks.

**Comment by raresn** [comment]
Voted! Thank you!
