### ISSUE TITLE
TextInput inside container with scale < 0 crops text

### ISSUE THREAD

**Issue by subdan** [BowlerHatLLC/feathers#1758]
Hello, Josh.

I have a Screen with .scale < 1. Inside the Screen I have a TextInput with scale = 1. After I type some text in to the TextInput and tap outside the TextInput text became cropped. As a workaround I set: textInput.scale = 1 / this.scale.

Is it a bug? How to fix it?

![symbol 1](https://user-images.githubusercontent.com/410293/44521686-335fe400-a6d4-11e8-9df6-04e0522cb1c5.png)

1. TextInput.scale = 1/ this.scale
2. TextInput.scale = 1

**Comment by joshtynjala** [comment]
Which ITextRenderer implementation are you using?

**Comment by subdan** [comment]
TextFieldTextRenderer

**Comment by joshtynjala** [comment]
As a workaround, you could set the useGutter property to true.

Actually, this is the same advice that I gave you in #1545.

**Comment by subdan** [comment]
Ok. Thanks.

**Comment by subdan** [comment]
I set useGutter=true and it did not helps.

**Comment by subdan** [comment]
The issue happens only on Android device.

**Comment by joshtynjala** [comment]
Does it look exactly the same when you set useGutter to true? You should see a couple more pixels of the text, even if there's still a bit cut off. If not, then it may actually be a rendering issue caused by the texture appearing on a non-integer pixel. Text tends to distort and blur unless it is positioned perfectly, and setting the scale of a parent container to a value other than 1 can affect the ability to snap to the nearest pixel.

I recommend changing the scale of containers that have text only during animations, when it will be difficult to see these sorts of issues.

**Comment by subdan** [comment]
Yes, it look exactly the same.
![screenshot_2018-08-25-17-55-20](https://user-images.githubusercontent.com/410293/44537016-0c1e0c80-a6fe-11e8-8d2b-f40a5ef36974.png)

**Comment by subdan** [comment]
I'm developing an Android app. I created GUI for 10" display. To display GUI on 7" display I scale down instances of Screen and PanelScreen. To calculate scale I use this code:

var screenDiagonalInches:Number = Math.sqrt(
					Math.pow(DeviceCapabilities.screenInchesX(Starling.current.nativeStage), 2) +
					Math.pow(DeviceCapabilities.screenInchesY(Starling.current.nativeStage), 2));
			
			if (screenDiagonalInches < 10)
				return screenDiagonalInches / 10;
			else
				return 1;
