### ISSUE TITLE
[Question] When item renderer drag&drop wil be released?

### ISSUE THREAD

**Issue by subdan** [BowlerHatLLC/feathers#1765]
Hello, Josh. When will you finish working on a drag&drop for List and ItemRenderer? I need this feature for my app.

**Comment by joshtynjala** [comment]
At the most basic, set dragEnabled and dropEnabled both to true on the List, and provide a dropIndicatorSkin. You will be able to drag and drop by dragging any item renderer automatically.

If you're using DefaultListItemRenderer, and you're on mobile, you should provide a dragIcon. When DefaultListItemRenderer has a dragIcon, only the icon will be able to start a drag rather than the entire item renderer.

I recently added drag and drop to the Todos example, so if you want to see some example code, that's probably the best place right now. It uses a custom item renderer based on LayoutGroupListItemRenderer instead of DefaultListItemRenderer, but you should at least be able to see how dragEnabled and dropEnabled can be used.

**Comment by subdan** [comment]
Thanks, Josh.
