### ISSUE TITLE
Pure ActionScript examples don't work

### ISSUE THREAD

**Issue by chrisvelevitch** [BowlerHatLLC/feathers#1776]
The pure ActionScript examples that come with 3.5.0 don't always work. For example, the HelloWorld example doesn't unless you change line 45 in `HelloWorldWeb.as`:-
```
var MainType:Class = getDefinitionByName("feathers.examples.helloWorld.Main") as Class;
```
to:-
```
var MainType:Class = feathers.examples.helloWorld.Main as Class;
```
Then is works. The same thing with the DrawersExplorer example.

My Feathers install was created with **Feathers SDK Manager** and I selected Feathers 3.5.0 and Air 31.0 and Flash Player 31.0.

Why is happening?

**Comment by joshtynjala** [comment]
The web versions of the examples are not distributed with the Feathers library. The code actually only exists so that I can build some SWFs to embed on feathersui.com.

However, if you want to build them, you need to use the -frame compiler option, like this:

-frame=two,feathers.examples.helloWorld.Main

This puts the Main class on frame 2 so that the first frame can load quickly and act as a preloader. You can see that I use the -frame compiler option in the build script.
