### ISSUE TITLE
GUI Editor development plan?

### ISSUE THREAD

**Issue by munggruel** [BowlerHatLLC/feathers#309]
In past , I used to program in Flex because of flash builder design view mode.Now Flash builder remove design view ,I can not accept this.
I hope that  feathers will contain a nice GUI Editor , this is very important.

**Comment by b005t3r** [comment]
@mikhailkuts having a UI components description format, like the JSONs you linked, would be great, but somehow I can't imagine editing that manually. I'd at least need an text editor with code completion and syntax checking for that.

**Comment by joshtynjala** [comment]
Just adding a link for Starling Builder:
http://wiki.starling-framework.org/builder/start

Also, closing this issue because it's outside of the scope of the core library. If any official Feathers editor were developed, it would be a separate project. Further discussion here is allowed, of course. :)
